name-template: 'Channeler v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'tests'
      - 'testing'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's New

  $CHANGES

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
      - '/maintenance\/.+/'
      - '/chore\/.+/'
    title:
      - '/docs/i'
      - '/maintenance/i'
      - '/chore/i'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
    title:
      - '/feature/i'
      - '/enhancement/i'